version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: example-web-server
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    command: npm start
    env_file:
      - ".env"
  redis:
    image: "redis:alpine3.12"
    ports:
      - "6379:6379"
    volumes:
      - "redisDB:/data"
  postgres:
    image: "postgres:12.3-alpine"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - "postgresDB:/var/lib/postgresql/data"

volumes:
  redisDB: {}
  postgresDB: {}
